# Site settings
title: Tifinly
email: lostguid.1@gmail.com
description: Moms food at your finger tips.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tifinly.com" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
# github_url:
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/tifinly
pinterest_url:
# slack_url:
twitter_url: https://twitter.com/tifinly

# Build settings
markdown: kramdown
